# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import judge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('AC', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('contain', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('context', models.TextField()),
                ('test', models.FileField(blank=True, null=True, upload_to=judge.models.generate_questionfilename)),
                ('ans', models.FileField(upload_to=judge.models.generate_questionfilename)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.member', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statue', models.CharField(default='waiting', max_length=20)),
                ('file', models.FileField(upload_to=judge.models.generate_submissionfilename)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.member', to_field='name')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem', to_field='title')),
            ],
        ),
    ]
