# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
