# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='AC',
            field=models.IntegerField(default=0),
        ),
    ]
