# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='file',
            new_name='code',
        ),
    ]
