# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_submission_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='statue',
            new_name='state',
        ),
    ]
