# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_auto_20170928_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='AC_problem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='AC',
            field=models.IntegerField(default=0),
        ),
    ]
