# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_auto_20170916_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='state',
            new_name='status',
        ),
    ]
