# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_auto_20170928_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='AC',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
