# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20170917_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='overview',
            field=models.CharField(default='No any introduce!', max_length=500),
        ),
        migrations.AddField(
            model_name='member',
            name='pphone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='sphone',
            field=models.IntegerField(default=0),
        ),
    ]
