# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import judge.models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_auto_20170929_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='samplein',
            field=models.TextField(default='(None)'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sampleout',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test',
            field=models.FileField(null=True, upload_to=judge.models.generate_questionfiletest),
        ),
    ]
