# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_auto_20170929_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='choice',
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='lang',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
