# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_auto_20170926_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='choice',
            field=models.CharField(blank=True, choices=[('C/C++', 'C/C++'), ('Python', 'Python'), ('Java', 'Java'), ('Web(HTML,CSS,JavaScript)', 'Web(HTML,CSS,JavaScript)')], max_length=100),
        ),
    ]
