# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_auto_20170930_1232'),
        ('judge', '0008_auto_20170930_0021'),
    ]

    operations = [
    ]
