# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 15:23
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_member_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='choice',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('C/C++', 'C/C++'), ('Python', 'Python'), ('Java', 'Java'), ('Web(HTML,CSS,JavaScript)', 'Web(HTML,CSS,JavaScript)')], max_length=42),
        ),
    ]
