# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import judge.models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0010_new_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='PDFcontext',
            field=models.FileField(blank=True, null=True, upload_to=judge.models.generate_PDF),
        ),
    ]
