# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0011_problem_pdfcontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='update',
            field=models.IntegerField(default=9223372036854775807),
        ),
        migrations.AlterField(
            model_name='problem',
            name='context',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sampleout',
            field=models.TextField(blank=True),
        ),
    ]
