# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0012_auto_20171015_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='update',
            field=models.IntegerField(default=0),
        ),
    ]
