# This dockerfile uses the ubuntu image
# VERSION 2 - EDITION 1
# Author: docker_user
# Command format: Instruction [arguments / command] ..

FROM ubuntu

RUN apt-get update  -y
RUN apt-get upgrade -y
RUN apt-get install python3 gcc g++ time -y

COPY run.sh run.sh

RUN chmod +x run.sh

ENTRYPOINT [ "sh", "run.sh" ]
